# Generated by Django 5.2.6 on 2025-09-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_auto_20250101_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userquizattempt',
            options={},
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='ease_factor',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='next_review',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='review_interval',
        ),
        migrations.RemoveField(
            model_name='userquizattempt',
            name='user',
        ),
        migrations.AddField(
            model_name='userquizattempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userquizattempt',
            name='session_key',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
